# Generated by Django 4.2.4 on 2024-04-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=2000)),
                ('titre', models.CharField(max_length=2000)),
                ('lieu', models.CharField(max_length=2000)),
                ('datee', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=2000)),
                ('image', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=2000)),
                ('titre', models.CharField(max_length=2000)),
                ('datee', models.CharField(max_length=2000)),
                ('desciption', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=5000)),
                ('langage', models.CharField(max_length=5000)),
            ],
        ),
    ]
